"""End-to-end behaviour of :class:`CoastalProcessor`.

The scene here is synthetic but not invented: rho_b and depth are prescribed,
and Rrs is generated by the forward Lee model using the saved Sesimbra IOP fit,
so the pipeline runs in the optical regime it was built for.

What is being pinned is not "the numbers are right" — the golden regression
does that. It is the contract around a run: that a rejected scene still writes
its products and says why, that a failure mode gets its own status instead of
an exception escaping, that the outputs land on one grid, and that nothing
downstream can mistake a diagnostic run for a measurement.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from oceanstream.coastal.aoi import AOI, BathymetryReference
from oceanstream.coastal.inversion.lee import forward_model
from oceanstream.coastal.io.rasters import RasterGrid, write_cog
from oceanstream.coastal.optics.qaa import SceneIOPs
from oceanstream.coastal.processor import (
    STATUS_EXECUTION_FAILED,
    STATUS_INSUFFICIENT_DATA,
    CoastalProcessor,
    InsufficientData,
    _depth_sign,
)
from oceanstream.coastal.products import STATUS_DIAGNOSTIC, STATUS_PUBLISHABLE
from oceanstream.coastal.scene import Scene

rasterio = pytest.importorskip("rasterio")

SOLAR_ZENITH_DEG = 21.0
SIZE = 48
#: Columns of shelf before the seaward drop-off.
SHELF_COLUMNS = 40
#: Sentinel-2 bands the processor needs: blue, blue-green, green, red,
#: red-edge, NIR, SWIR1, SWIR2. Both SWIR bands are required — the deep-water
#: screen keys on 2191 nm and the scene validator refuses to run without it.
BANDS_NM = (444.0, 489.0, 561.0, 667.0, 707.0, 835.0, 1612.0, 2191.0)


def test_registered_reference_is_applied_before_sampling(aoi, scene, tmp_path, monkeypatch):
    from dataclasses import replace

    from rasterio.warp import transform_geom

    from oceanstream.coastal.config import MaskConfig, RetrievalConfig
    from oceanstream.coastal.stages import prepare_scene

    # A small offshore patch has ample qualifying pixels, even when it is a
    # small fraction of the whole scene's deep-water population.
    patch = tmp_path / "reference.geojson"
    geometry = transform_geom(
        "EPSG:32629",
        "EPSG:4326",
        {
            "type": "Polygon",
            "coordinates": [
                [
                    [500460, 4255520],
                    [500480, 4255520],
                    [500480, 4256000],
                    [500460, 4256000],
                    [500460, 4255520],
                ]
            ],
        },
    )
    patch.write_text(
        json.dumps(
            {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "properties": {},
                        "geometry": geometry,
                    }
                ],
            }
        )
    )
    registered = replace(
        aoi,
        deepwater_reference_uri=str(patch),
        metadata={
            "regions_preregistered": False,
            "reporting_area_provisional": True,
        },
    )
    monkeypatch.setattr(
        "oceanstream.coastal.stages.kd_map",
        lambda *args, **kwargs: np.ones(scene.shape, np.float32),
    )
    prepared = prepare_scene(registered, scene, mask_config=MaskConfig(deepwater_max_samples=50))
    assert prepared.deep.sum() == 50
    assert not prepared.deep[:, :46].any()
    assert prepared.provenance["coverage"]["deep_candidates_before_sampling"] == 96
    assert {"calibration_regions_exploratory", "reporting_area_provisional"} <= set(prepared.flags)
    failed = CoastalProcessor(config=RetrievalConfig(min_deep_pixels=10_000)).run(
        registered, scene, tmp_path / "failed"
    )
    assert failed.status == STATUS_INSUFFICIENT_DATA and not failed.success
    failure = json.loads((failed.output_dir / "failure.json").read_text())
    assert failure["diagnostics"]["depth_reference"]["coverage"]["deep_pixels"] == 96
    assert not (failed.output_dir / "manifest.json").exists()


def _transect(shelf_max_m: float) -> np.ndarray:
    """A shelf that shoals inshore, then a drop-off on the seaward edge.

    A single linear ramp cannot satisfy both ends of this pipeline. The QAA fit
    needs optically deep water — z > 30 m *and* z·Kd(490) > 6, so past ~70 m at
    Sesimbra — while the bottom retrieval needs water shallow enough for red
    light to make the round trip. So the shelf carries most of the grid and the
    last eight columns fall away to 140 m.
    """
    ramp = np.empty(SIZE, dtype=np.float64)
    ramp[:SHELF_COLUMNS] = np.linspace(0.5, shelf_max_m, SHELF_COLUMNS)
    ramp[SHELF_COLUMNS:] = np.linspace(40.0, 140.0, SIZE - SHELF_COLUMNS)
    return np.tile(ramp, (SIZE, 1))


def _single_band(iops: SceneIOPs, index: int) -> SceneIOPs:
    """One band's IOPs, so the forward model broadcasts against a 2-D grid."""
    return SceneIOPs(
        wavelengths_nm=iops.wavelengths_nm[index : index + 1],
        a=iops.a[index : index + 1],
        bb=iops.bb[index : index + 1],
        kd=iops.kd[index : index + 1],
        a_cdm_443=iops.a_cdm_443,
        bbp_555=iops.bbp_555,
        y=iops.y,
        n_deep_pixels=iops.n_deep_pixels,
        ref_wavelength_nm=iops.ref_wavelength_nm,
    )


@pytest.fixture
def grid() -> RasterGrid:
    """A 10 m UTM 29N grid off Sesimbra — the real projection, small extent."""
    return RasterGrid(
        width=SIZE,
        height=SIZE,
        transform=(10.0, 0.0, 500000.0, 0.0, -10.0, 4256000.0),
        crs="EPSG:32629",
    )


@pytest.fixture
def truth_depth() -> np.ndarray:
    """The reference surface: a 22 m shelf with a drop-off, positive down."""
    return _transect(22.0)


@pytest.fixture
def iops(scene_iops_raw: dict) -> SceneIOPs:
    """Full-spectrum Sesimbra IOPs interpolated onto the synthetic band set.

    Floored at pure water. The saved Sesimbra fit sits *below* the pure-water
    absorption floor at 667 nm and 707 nm — that is the known additive
    atmospheric-correction bias this library exists to flag, not a property of
    the sea. Generating a scene from it would produce Rrs no water column can
    make, and the retrieval would then correctly refuse to invert it. The floor
    keeps the synthetic experiment inside physics.
    """
    from oceanstream.coastal.optics import water

    source = np.asarray(scene_iops_raw["wavelengths_nm"], dtype=float)
    target = np.asarray(BANDS_NM, dtype=float)

    def resample(key: str) -> np.ndarray:
        return np.interp(target, source, np.asarray(scene_iops_raw[key], dtype=float))

    a = np.maximum(resample("a"), np.asarray(water.a_water(target), dtype=float))
    bb = np.maximum(resample("bb"), np.asarray(water.bb_water(target), dtype=float))

    return SceneIOPs(
        wavelengths_nm=target,
        a=a,
        bb=bb,
        kd=resample("kd"),
        a_cdm_443=float(scene_iops_raw.get("a_cdm_443") or np.nan),
        bbp_555=float("nan"),
        y=float("nan"),
        n_deep_pixels=5000,
        ref_wavelength_nm=561.0,
    )


@pytest.fixture
def bathymetry(tmp_path: Path, grid: RasterGrid, truth_depth: np.ndarray) -> Path:
    """The reference surface, tagged positive=down as EMODnet exports are."""
    path = tmp_path / "bathymetry.tif"
    write_cog(path, truth_depth.astype(np.float32), grid, tags={"positive": "down"})
    return path


@pytest.fixture
def aoi(bathymetry: Path) -> AOI:
    return AOI(
        name="synthetic-sesimbra",
        processing_bbox=(-9.05, 38.40, -8.95, 38.48),
        label="Synthetic Sesimbra",
        fine_bathymetry=BathymetryReference(
            uri=str(bathymetry), resolution_m=10.0, attribution="synthetic"
        ),
    )


@pytest.fixture
def scene(grid: RasterGrid, truth_depth: np.ndarray, iops: SceneIOPs) -> Scene:
    """Rrs generated forward from a two-substrate seabed."""
    return _build_scene(grid, truth_depth, iops, noise_sigma=2e-5)


def _build_scene(
    grid: RasterGrid,
    depth: np.ndarray,
    iops: SceneIOPs,
    *,
    noise_sigma: float,
) -> Scene:
    rng = np.random.default_rng(20260627)
    n_bands = len(BANDS_NM)

    # Two substrates: bright sand and dark vegetation, in vertical stripes so
    # both are present at every depth.
    bright = np.array([0.10, 0.13, 0.17, 0.19, 0.20, 0.21, 0.0, 0.0])
    dark = np.array([0.02, 0.025, 0.045, 0.030, 0.055, 0.070, 0.0, 0.0])
    is_bright = (np.arange(SIZE)[None, :] // 6) % 2 == 0
    rho_b = np.where(
        is_bright[None, :, :],
        bright[:, None, None],
        dark[:, None, None],
    ).astype(np.float64)

    # forward_model broadcasts IOPs against the depth grid, so it has to be
    # driven one band at a time.
    rrs = np.stack(
        [
            forward_model(rho_b[i], depth, _single_band(iops, i), SOLAR_ZENITH_DEG)
            for i in range(n_bands)
        ]
    )
    rrs = rrs + rng.normal(0.0, noise_sigma, rrs.shape)

    # rhos: above-water surface reflectance. SWIR is dark over water, which is
    # what the composite mask keys on.
    rhos = np.clip(rrs * np.pi, 0.0, None)
    rhos[BANDS_NM.index(1612.0)] = 0.002
    rhos[BANDS_NM.index(2191.0)] = 0.001
    rhos[BANDS_NM.index(835.0)] = np.clip(rhos[BANDS_NM.index(835.0)], 0.0, 0.01)

    return Scene.from_arrays(
        wavelengths_nm=BANDS_NM,
        rrs_above=rrs,
        grid=grid,
        solar_zenith_deg=SOLAR_ZENITH_DEG,
        sensor="sentinel2",
        rhos=rhos,
        acquisition_date=None,
        metadata={"synthetic": True},
    )


@pytest.fixture
def result(aoi: AOI, scene: Scene, tmp_path: Path):
    processor = CoastalProcessor(campaign_id="unit-test")
    return processor.run(aoi, scene, tmp_path / "out")


# ---------------------------------------------------------------------------
# The run completes and reports a status
# ---------------------------------------------------------------------------


class TestRunCompletes:
    def test_the_run_does_not_raise(self, result):
        assert result.message, result.message

    def test_the_run_reports_one_of_the_four_defined_statuses(self, result):
        assert result.status in {
            "passed",
            "rejected",
            STATUS_INSUFFICIENT_DATA,
            STATUS_EXECUTION_FAILED,
        }

    def test_a_completed_run_is_marked_successful(self, result):
        assert result.success, result.message

    def test_success_and_acceptance_are_separate_questions(self, result):
        """A run can finish cleanly and still be inadmissible."""
        assert result.success
        assert result.accepted == (result.status == "passed")

    def test_the_campaign_and_aoi_are_carried_through(self, result):
        assert result.campaign_id == "unit-test"
        assert result.aoi_name == "synthetic-sesimbra"


# ---------------------------------------------------------------------------
# Products
# ---------------------------------------------------------------------------


class TestProducts:
    def test_the_expected_products_are_written(self, result):
        for key in (
            "sdb_depth",
            "optical_depth",
            "seabed_par",
            "detectability_margin",
            "detectable",
            "spectral_class",
            "attenuation",
            "detectability",
            "iops",
            "qc",
            "report",
        ):
            assert key in result.products, f"missing {key}"

    def test_one_rho_b_raster_per_visible_band(self, result):
        rho_b_keys = {
            k
            for k in result.products
            if k.startswith("rho_b_") and not k.startswith("rho_b_sigma_")
        }
        assert rho_b_keys == {
            "rho_b_444",
            "rho_b_489",
            "rho_b_561",
            "rho_b_667",
        }

    def test_swir_never_becomes_a_benthic_product(self, result):
        assert "rho_b_1612" not in result.products
        assert "rho_b_2191" not in result.products

    def test_every_product_exists_on_disk(self, result):
        for key, href in result.products.items():
            assert Path(href).exists(), f"{key} at {href}"

    def test_every_raster_shares_the_run_grid(self, result, grid):
        for key, href in result.products.items():
            if not href.endswith(".tif"):
                continue
            with rasterio.open(href) as src:
                assert (src.width, src.height) == (grid.width, grid.height), key
                assert src.crs.to_string() == grid.crs, key

    def test_the_status_tag_matches_the_verdict(self, result):
        expected = STATUS_PUBLISHABLE if result.accepted else STATUS_DIAGNOSTIC
        with rasterio.open(result.products["sdb_depth"]) as src:
            assert src.tags()["OCEANSTREAM_STATUS"] == expected

    def test_the_provenance_reaches_the_rasters(self, result):
        with rasterio.open(result.products["sdb_depth"]) as src:
            tags = src.tags()
        assert tags["OCEANSTREAM_AOI"] == "synthetic-sesimbra"
        assert tags["OCEANSTREAM_CAMPAIGN_ID"] == "unit-test"
        assert float(tags["OCEANSTREAM_SOLAR_ZENITH_DEG"]) == pytest.approx(
            SOLAR_ZENITH_DEG, abs=1e-3
        )

    def test_the_class_raster_uses_negative_one_for_nodata_not_class_zero(self, result):
        with rasterio.open(result.products["spectral_class"]) as src:
            assert src.nodata == -1
            assert src.dtypes[0] == "int16"


# ---------------------------------------------------------------------------
# Physics recovered from the synthetic scene
# ---------------------------------------------------------------------------


class TestPhysics:
    def test_the_retrieval_recovers_the_prescribed_depth_gradient(self, result, truth_depth):
        with rasterio.open(result.products["sdb_depth"]) as src:
            depth = src.read(1)
        finite = np.isfinite(depth)
        assert finite.sum() > 0
        assert np.corrcoef(depth[finite], truth_depth[finite])[0, 1] > 0.9

    def test_shallow_water_lets_more_par_reach_the_seabed_than_deep(self, result):
        with rasterio.open(result.products["seabed_par"]) as src:
            par = src.read(1)
        assert np.nanmean(par[:, :8]) > np.nanmean(par[:, -8:])

    def test_the_detectability_margin_shrinks_with_depth(self, result):
        with rasterio.open(result.products["detectability_margin"]) as src:
            margin = src.read(1)
        assert np.nanmean(margin[:, :8]) > np.nanmean(margin[:, -8:])

    def test_the_two_prescribed_substrates_separate_into_classes(self, result):
        with rasterio.open(result.products["spectral_class"]) as src:
            labels = src.read(1)
        assert len(set(np.unique(labels)) - {-1}) >= 2

    def test_attenuation_is_reported_for_every_visible_band(self, result):
        payload = json.loads(Path(result.products["attenuation"]).read_text())
        bands = payload["attenuation"]["k_by_band"]
        assert len(bands) >= 4
        assert all(np.isfinite(v) for v in bands.values())


# ---------------------------------------------------------------------------
# QC and STAC
# ---------------------------------------------------------------------------


class TestVerdict:
    def test_the_verdict_is_on_the_result(self, result):
        assert "passed" in result.qc_verdict

    def test_the_verdict_is_written_as_a_product(self, result):
        payload = json.loads(Path(result.products["qc"]).read_text())
        assert "floors" in payload["qc"]
        assert "ac_uncertainty" in payload["qc"]

    def test_the_qc_document_records_how_many_pixels_survived_each_stage(self, result):
        payload = json.loads(Path(result.products["qc"]).read_text())["qc"]
        assert payload["n_valid_pixels"] > 0
        assert payload["n_deep_pixels"] > 0
        assert payload["n_invertible_pixels"] > 0

    def test_a_stac_item_is_emitted_carrying_the_verdict(self, result):
        assert result.stac_item is not None
        item = json.loads(result.stac_item.read_text())
        assert "passed" in item["properties"]["oceanstream:qc"]

    def test_the_stac_bbox_is_lonlat_despite_the_utm_grid(self, result):
        item = json.loads(result.stac_item.read_text())
        west, south, east, north = item["bbox"]
        assert -10.0 < west < -8.0
        assert 38.0 < south < 39.0

    def test_stac_can_be_switched_off(self, aoi, scene, tmp_path):
        out = CoastalProcessor().run(aoi, scene, tmp_path / "nostac", emit_stac=False)
        assert out.stac_item is None
        assert out.products


# ---------------------------------------------------------------------------
# Failure modes are named, not raised
# ---------------------------------------------------------------------------


class TestFailureModes:
    def test_an_aoi_without_bathymetry_is_insufficient_data_not_a_crash(self, scene, tmp_path):
        bare = AOI(name="no-bathy", processing_bbox=(-9.05, 38.40, -8.95, 38.48))
        result = CoastalProcessor().run(bare, scene, tmp_path / "out")
        assert result.status == STATUS_INSUFFICIENT_DATA
        assert not result.success
        assert "bathymetry" in result.message

    def test_the_insufficient_data_message_says_what_to_supply(self, scene, tmp_path):
        bare = AOI(name="no-bathy", processing_bbox=(-9.05, 38.40, -8.95, 38.48))
        result = CoastalProcessor().run(bare, scene, tmp_path / "out")
        assert "fine_bathymetry" in result.message

    def test_an_all_cloud_scene_is_insufficient_data(self, aoi, scene, grid, tmp_path):
        opaque = Scene.from_arrays(
            wavelengths_nm=BANDS_NM,
            rrs_above=scene.rrs_above,
            grid=grid,
            solar_zenith_deg=SOLAR_ZENITH_DEG,
            sensor="sentinel2",
            rhos=np.full_like(scene.rhos, 0.6),
        )
        result = CoastalProcessor().run(aoi, opaque, tmp_path / "out")
        assert result.status == STATUS_INSUFFICIENT_DATA
        assert "mask" in result.message.lower() or "pixel" in result.message.lower()

    def test_an_unexpected_error_is_reported_not_propagated(
        self, aoi, scene, tmp_path, monkeypatch
    ):
        def boom(*args, **kwargs):
            raise RuntimeError("kaboom")

        monkeypatch.setattr("oceanstream.coastal.optics.qaa.fit_scene_iops", boom, raising=True)
        result = CoastalProcessor().run(aoi, scene, tmp_path / "out")
        assert result.status == STATUS_EXECUTION_FAILED
        assert "kaboom" in result.message
        assert not result.success


class TestDepthSign:
    def test_a_positive_down_tag_is_believed(self, tmp_path, grid, truth_depth):
        path = tmp_path / "down.tif"
        write_cog(path, truth_depth.astype(np.float32), grid, tags={"positive": "down"})
        sign, source = _depth_sign(truth_depth, str(path))
        assert sign == 1.0
        assert "tag" in source

    def test_a_positive_up_tag_flips_the_sign(self, tmp_path, grid, truth_depth):
        path = tmp_path / "up.tif"
        write_cog(path, -truth_depth.astype(np.float32), grid, tags={"positive": "up"})
        sign, source = _depth_sign(-truth_depth, str(path))
        assert sign == -1.0

    def test_without_a_tag_the_median_decides(self, tmp_path, grid, truth_depth):
        path = tmp_path / "untagged.tif"
        write_cog(path, -truth_depth.astype(np.float32), grid)
        sign, source = _depth_sign(-truth_depth, str(path))
        assert sign == -1.0
        assert "median" in source

    def test_an_ambiguous_grid_is_refused_rather_than_guessed(self, tmp_path):
        near_zero = np.linspace(-0.5, 0.5, 100)
        with pytest.raises(InsufficientData, match="positive-up or positive-down"):
            _depth_sign(near_zero, str(tmp_path / "missing.tif"))

    def test_a_grid_with_no_overlap_says_so(self, tmp_path):
        with pytest.raises(InsufficientData, match="overlap"):
            _depth_sign(np.full(10, np.nan), str(tmp_path / "missing.tif"))


# ---------------------------------------------------------------------------
# The command line
# ---------------------------------------------------------------------------


class TestCommandLine:
    """`process coastal detect` over a real ACOLITE-shaped directory.

    The processor is exercised directly everywhere above; what is unproven
    until here is the wiring — that the AOI and scene loaders accept what the
    library writes, that the exit code carries the QC verdict, and that a
    rejected scene is still a zero exit unless the caller asks otherwise.
    """

    @pytest.fixture
    def acolite_dir(self, tmp_path: Path, grid: RasterGrid, scene: Scene) -> Path:
        """Write the synthetic scene the way ACOLITE writes an L2R product."""
        directory = tmp_path / "acolite"
        directory.mkdir()
        assert scene.rhos is not None
        for i, nm in enumerate(BANDS_NM):
            write_cog(
                directory / f"S2A_MSI_2026_09_10_L2R_rhos_{int(nm)}.tif",
                scene.rhos[i].astype(np.float32),
                grid,
            )
        return directory

    @pytest.fixture
    def aoi_json(self, tmp_path: Path, aoi: AOI) -> Path:
        path = tmp_path / "aoi.json"
        path.write_text(json.dumps(aoi.to_dict()))
        return path

    def _run(self, *args: str):
        from typer.testing import CliRunner

        from oceanstream import cli as cli_module

        return CliRunner().invoke(cli_module.app, list(args))

    def test_detect_exits_zero_and_writes_a_stac_item(
        self, tmp_path: Path, aoi_json: Path, acolite_dir: Path
    ):
        out = tmp_path / "cli-out"
        result = self._run(
            "process",
            "coastal",
            "detect",
            "--aoi",
            str(aoi_json),
            "--scene",
            str(acolite_dir),
            "--output-dir",
            str(out),
            "--solar-zenith",
            str(SOLAR_ZENITH_DEG),
            "--campaign-id",
            "cli-test",
            "--yes",
        )
        assert result.exit_code == 0, result.output

        from oceanstream.coastal.provenance import resolve_run

        items = list((resolve_run(out) / "stac" / "items").glob("*.json"))
        assert items, f"no STAC item written under {out}"
        item = json.loads(items[0].read_text())
        assert item["properties"]["oceanstream:qc"]["passed"] in {True, False}

    def test_a_rejected_scene_exits_three_only_when_asked(
        self, tmp_path: Path, aoi_json: Path, acolite_dir: Path
    ):
        """QC rejection is a finding, not a crash — the caller opts into it."""
        result = self._run(
            "process",
            "coastal",
            "detect",
            "--aoi",
            str(aoi_json),
            "--scene",
            str(acolite_dir),
            "--output-dir",
            str(tmp_path / "strict"),
            "--solar-zenith",
            str(SOLAR_ZENITH_DEG),
            "--fail-on-reject",
            "--yes",
        )
        # This synthetic scene inherits Sesimbra's sub-floor red bands, so it
        # is expected to fail the pure-water gate.
        assert result.exit_code == 3, result.output

    def test_dry_run_writes_nothing(self, tmp_path: Path, aoi_json: Path, acolite_dir: Path):
        out = tmp_path / "dry"
        result = self._run(
            "process",
            "coastal",
            "detect",
            "--aoi",
            str(aoi_json),
            "--scene",
            str(acolite_dir),
            "--output-dir",
            str(out),
            "--dry-run",
        )
        assert result.exit_code == 0, result.output
        assert not out.exists() or not list(out.rglob("*.tif"))


class TestAOIOnboardingCLI:
    """`coastal aoi --discover-bathymetry` joins four EMODnet calls.

    The point of the flag is that onboarding a new site is one command. What is
    worth pinning down is that it selects the *finest* area rather than the
    first, that a site with no coverage still yields an AOI (a coarse-DTM
    fallback is a degraded result, not a failed one), and that seabed stability
    is never invented — EMODnet does not publish it, and asserting it wrongly
    changes what the product may claim.
    """

    SESIMBRA = "-9.15,38.39,-8.90,38.51"

    def _run(self, *args: str):
        from typer.testing import CliRunner

        from oceanstream import cli as cli_module

        return CliRunner().invoke(cli_module.app, list(args))

    @staticmethod
    def _areas(monkeypatch, areas):
        from oceanstream.coastal.bathymetry import emodnet

        monkeypatch.setattr(emodnet, "discover_hr_areas", lambda *a, **k: areas)

    @staticmethod
    def _area(identifier, denom, url="https://example.invalid/x.zip", year=2020):
        from oceanstream.coastal.bathymetry.emodnet import HRArea

        return HRArea(
            identifier=identifier,
            resolution_arcmin_denom=denom,
            download_url=url,
            edmo_id=590,
            product_year=year,
        )

    def test_it_records_the_finest_area_not_the_first(self, tmp_path, monkeypatch):
        self._areas(
            monkeypatch,
            [self._area("HR_Lidar_Sul", 128), self._area("HR_Setubal", 64)],
        )
        result = self._run(
            "process",
            "coastal",
            "aoi",
            "sesimbra",
            "--bbox",
            self.SESIMBRA,
            "--discover-bathymetry",
            "--seabed-stability",
            "stable_rock",
            "-o",
            str(tmp_path),
        )
        assert result.exit_code == 0, result.output
        record = json.loads((tmp_path / "sesimbra.json").read_text())
        reference = record["fine_bathymetry"]
        assert "HR_Lidar_Sul" in reference["attribution"]
        assert reference["resolution_m"] == pytest.approx(14.469, abs=1e-3)
        assert reference["seabed_stability"] == "stable_rock"
        assert reference["vertical_datum"] == "LAT"

    def test_no_coverage_still_writes_an_aoi(self, tmp_path, monkeypatch):
        """No HR tile is a coarse-DTM fallback, not a failed onboarding."""
        self._areas(monkeypatch, [])
        result = self._run(
            "process",
            "coastal",
            "aoi",
            "galicia",
            "--bbox",
            "-9.1,42.1,-8.6,42.7",
            "--discover-bathymetry",
            "-o",
            str(tmp_path),
        )
        assert result.exit_code == 0, result.output
        record = json.loads((tmp_path / "galicia.json").read_text())
        assert record.get("fine_bathymetry") is None
        assert "115 m" in result.output

    def test_stability_is_left_unasserted_when_not_given(self, tmp_path, monkeypatch):
        self._areas(monkeypatch, [self._area("HR_Lidar_Sul", 128)])
        result = self._run(
            "process",
            "coastal",
            "aoi",
            "sesimbra",
            "--bbox",
            self.SESIMBRA,
            "--discover-bathymetry",
            "-o",
            str(tmp_path),
        )
        assert result.exit_code == 0, result.output
        record = json.loads((tmp_path / "sesimbra.json").read_text())
        assert record["fine_bathymetry"]["seabed_stability"] is None

    def test_an_invalid_stability_value_is_refused(self, tmp_path, monkeypatch):
        self._areas(monkeypatch, [self._area("HR_Lidar_Sul", 128)])
        result = self._run(
            "process",
            "coastal",
            "aoi",
            "sesimbra",
            "--bbox",
            self.SESIMBRA,
            "--discover-bathymetry",
            "--seabed-stability",
            "probably_rock",
            "-o",
            str(tmp_path),
        )
        assert result.exit_code != 0
        assert not (tmp_path / "sesimbra.json").exists()

    def test_discovery_is_skipped_unless_asked(self, tmp_path, monkeypatch):
        """The default path must not reach the network."""

        def _boom(*a, **k):
            raise AssertionError("discover_hr_areas must not be called")

        from oceanstream.coastal.bathymetry import emodnet

        monkeypatch.setattr(emodnet, "discover_hr_areas", _boom)
        result = self._run(
            "process",
            "coastal",
            "aoi",
            "plain",
            "--bbox",
            self.SESIMBRA,
            "-o",
            str(tmp_path),
        )
        assert result.exit_code == 0, result.output
        assert json.loads((tmp_path / "plain.json").read_text())["name"] == "plain"


class TestBetaContracts:
    def test_stac_failure_is_not_success_and_cannot_complete(
        self, aoi, scene, tmp_path, monkeypatch
    ):
        from oceanstream.coastal.stac import coastal_emit

        def fail(*args, **kwargs):
            raise OSError("simulated STAC write failure")

        monkeypatch.setattr(coastal_emit, "emit_stac", fail)
        result = CoastalProcessor().run(aoi, scene, tmp_path / "out")
        assert not result.success and not result.accepted
        assert result.status == STATUS_EXECUTION_FAILED
        assert "STAC" in result.message
        assert not (result.output_dir / "manifest.json").exists()
        assert not (tmp_path / "out" / "latest.json").exists()

    def test_reruns_are_isolated_and_failure_preserves_last_complete_run(
        self, aoi, scene, tmp_path, monkeypatch
    ):
        from oceanstream.coastal.provenance import resolve_run
        from oceanstream.coastal.stac import coastal_emit

        root = tmp_path / "out"
        first = CoastalProcessor().run(aoi, scene, root)
        assert first.success
        (first.output_dir / "stale.tif").write_text("previous run")
        second = CoastalProcessor().run(aoi, scene, root)
        assert second.success and first.output_dir != second.output_dir
        assert not (second.output_dir / "stale.tif").exists()
        assert resolve_run(root) == second.output_dir

        def fail(*args, **kwargs):
            raise OSError("disk failure")

        monkeypatch.setattr(coastal_emit, "emit_stac", fail)
        third = CoastalProcessor().run(aoi, scene, root)
        assert not third.success
        assert resolve_run(root) == second.output_dir

    def test_product_verdicts_survive_json_raster_and_stac(self, result):
        assert result.success and not result.accepted
        with rasterio.open(result.products["valid_water"]) as source:
            assert source.tags()["OCEANSTREAM_QC_PASSED"] == "True"
        with rasterio.open(result.products["seabed_par"]) as source:
            assert source.tags()["OCEANSTREAM_QC_PASSED"] == "False"
        item = json.loads(result.stac_item.read_text())
        assert item["assets"]["valid_water"]["oceanstream:status"] == "publishable"
        assert item["assets"]["seabed_par"]["oceanstream:status"] == "diagnostic_only"
        detection = json.loads(Path(result.products["detectability"]).read_text())
        assert not detection["oceanstream:qc"]["passed"]
        assert detection["detectability"]["status"] == "diagnostic_only"

    def test_cli_detect_failed_write_has_nonzero_exit(self, aoi, scene, tmp_path, monkeypatch):
        from typer.testing import CliRunner

        from oceanstream.cli import app
        from oceanstream.coastal.stac import coastal_emit

        # Feed the complete command through the public scene loader.
        monkeypatch.setattr(Scene, "from_acolite_dir", lambda *a, **kw: scene)

        def fail(*args, **kwargs):
            raise OSError("STAC write failure")

        monkeypatch.setattr(coastal_emit, "emit_stac", fail)
        config_path = tmp_path / "aoi.json"
        config_path.write_text(json.dumps(aoi.to_dict()))
        outcome = CliRunner().invoke(
            app,
            [
                "process",
                "coastal",
                "detect",
                "--aoi",
                str(config_path),
                "--scene",
                str(tmp_path),
                "-o",
                str(tmp_path / "out"),
            ],
        )
        assert outcome.exit_code != 0
        assert not (tmp_path / "out" / "latest.json").exists()

    def test_cli_attenuation_and_compare_use_processor_results(
        self, aoi, scene, tmp_path, monkeypatch
    ):
        from typer.testing import CliRunner

        from oceanstream.cli import app
        from oceanstream.coastal.compare import scene_optics
        from oceanstream.coastal.provenance import resolve_run

        monkeypatch.setattr(Scene, "from_acolite_dir", lambda *a, **kw: scene)
        config_path = tmp_path / "aoi.json"
        config_path.write_text(json.dumps(aoi.to_dict()))
        output = tmp_path / "out"
        outcome = CliRunner().invoke(
            app,
            [
                "process",
                "coastal",
                "attenuation",
                "--aoi",
                str(config_path),
                "--acolite-dir",
                str(tmp_path),
                "--bathymetry",
                aoi.fine_bathymetry.uri,
                "-o",
                str(output),
            ],
        )
        assert outcome.exit_code == 0, outcome.exception
        saved = json.loads((resolve_run(output) / "attenuation.json").read_text())["attenuation"]
        comparison = scene_optics("synthetic", tmp_path, aoi.fine_bathymetry.uri, aoi=aoi)
        assert comparison.verdict == saved["verdict"]
        assert comparison.bands["green"]["k_per_m"] == saved["bands"]["561.0"]["k_per_m"]

    def test_attenuation_uses_independent_depth_even_when_sdb_changes(
        self, aoi, scene, tmp_path, monkeypatch
    ):
        from oceanstream.coastal.bathymetry import stumpf

        first = CoastalProcessor().run(aoi, scene, tmp_path / "one", emit_stac=False)
        monkeypatch.setattr(
            stumpf, "apply_stumpf", lambda *args, **kwargs: np.full(scene.shape, 2.0)
        )
        second = CoastalProcessor().run(aoi, scene, tmp_path / "two", emit_stac=False)
        a = json.loads(Path(first.products["attenuation"]).read_text())["attenuation"]
        b = json.loads(Path(second.products["attenuation"]).read_text())["attenuation"]
        assert a == b

    def test_fine_depth_and_offshore_coarse_reference_have_distinct_roles(
        self, aoi, scene, truth_depth, grid, tmp_path
    ):
        from dataclasses import replace

        from oceanstream.coastal.stages import prepare_scene

        fine = truth_depth.copy()
        fine[:, SHELF_COLUMNS:] = np.nan
        fine_path, coarse_path = tmp_path / "fine.tif", tmp_path / "coarse.tif"
        write_cog(fine_path, fine, grid, tags={"positive": "down"})
        write_cog(coarse_path, truth_depth + 3, grid, tags={"positive": "down"})
        configured = replace(
            aoi,
            fine_bathymetry=BathymetryReference(uri=str(fine_path)),
            coarse_bathymetry=BathymetryReference(uri=str(coarse_path)),
        )
        prepared = prepare_scene(configured, scene)
        np.testing.assert_allclose(prepared.depth[:, :SHELF_COLUMNS], fine[:, :SHELF_COLUMNS])
        np.testing.assert_allclose(prepared.deep_depth, truth_depth + 3)
        assert prepared.deep.any()

    def test_tide_correction_requires_acquisition_time_and_matching_datum(self, aoi, scene):
        import datetime as dt
        from dataclasses import replace

        from oceanstream.coastal.bathymetry.tide import TideCorrection
        from oceanstream.coastal.stages import prepare_scene

        when = dt.datetime.combine(scene.acquisition_date, dt.time(12), tzinfo=dt.UTC)
        configured = replace(scene, acquisition_datetime=when)
        tide = TideCorrection(
            1.0,
            "model",
            "test gauge",
            when=when,
            uncertainty_m=0.2,
            metadata={"vertical_datum": "LAT"},
        )
        corrected = prepare_scene(aoi, configured, tide=tide)
        original = prepare_scene(aoi, configured)
        np.testing.assert_allclose(corrected.depth, original.depth + 1)
        np.testing.assert_allclose(
            corrected.depth_sigma**2, original.depth_sigma**2 + 0.04, rtol=1e-5
        )
        assert "tide_correction_missing" not in corrected.flags
        with pytest.raises(ValueError, match="same timezone-aware acquisition time"):
            prepare_scene(aoi, scene, tide=tide)
        with pytest.raises(ValueError, match="datum"):
            prepare_scene(aoi, configured, tide=replace(tide, metadata={"vertical_datum": "MSL"}))

    def test_declared_regions_and_depth_limits_mask_reporting(self, aoi, scene, tmp_path):
        from dataclasses import replace

        from oceanstream.coastal.stac.coastal_emit import bbox_polygon
        from oceanstream.coastal.stages import prepare_scene

        path = tmp_path / "regions.geojson"
        path.write_text(
            json.dumps(
                {
                    "type": "FeatureCollection",
                    "features": [
                        {
                            "type": "Feature",
                            "properties": {"region_id": "registered"},
                            "geometry": bbox_polygon(aoi.processing_bbox),
                        }
                    ],
                }
            )
        )
        configured = replace(
            aoi,
            attenuation_regions_uri=str(path),
            habitat_bbox=aoi.processing_bbox,
            deepwater_reference_uri=str(path),
            depth_valid_range_m=(5.0, 10.0),
        )
        prepared = prepare_scene(configured, scene)
        assert set(prepared.regions) == {"registered"}
        assert prepared.reporting.any()
        assert (
            (prepared.depth[prepared.reporting] >= 5) & (prepared.depth[prepared.reporting] <= 10)
        ).all()
        assert "calibration_regions_not_registered" not in prepared.flags

    def test_output_stac_validates_against_every_declared_schema(self, result):
        import jsonschema
        from referencing import Registry, Resource
        from referencing.jsonschema import DRAFT7

        root = Path(__file__).resolve().parents[2] / "data" / "coastal" / "stac_schemas"
        schemas = {
            uri: json.loads((root / name).read_text())
            for uri, name in json.loads((root / "index.json").read_text()).items()
        }
        registry = Registry().with_resources(
            (uri, Resource.from_contents(schema, default_specification=DRAFT7))
            for uri, schema in schemas.items()
        )
        for path, core in ((result.stac_item, "item"), (result.stac_collection, "collection")):
            document = json.loads(path.read_text())
            url = f"https://schemas.stacspec.org/v1.0.0/{core}-spec/json-schema/{core}.json"
            for uri in [url, *document.get("stac_extensions", [])]:
                jsonschema.Draft7Validator(
                    schemas[uri], registry=registry, format_checker=jsonschema.FormatChecker()
                ).validate(document)
